pirogramming/PiroCheck

- frontend/src/root.module.css
> [add]: root.module.css 추가

- backend/pirocheck/src/main/java/backend/pirocheck/Deposit/controller/DepositController.java
- backend/pirocheck/src/main/java/backend/pirocheck/Deposit/service/DepositService.java
> [feat] Deposit 수정

- frontend/src/Attendance.jsx
> [del]: boom img

- backend/pirocheck/src/main/java/backend/pirocheck/Deposit/service/DepositService.java
- backend/pirocheck/src/main/java/backend/pirocheck/assignment/repository/AssignmentRepository.java
> [feat] Deposit 코드 추가

- backend/pirocheck/src/main/java/backend/pirocheck/User/config/SessionCheckFilterConfig.java
- backend/pirocheck/src/main/java/backend/pirocheck/User/exception/GlobalExceptionHandler.java
- backend/pirocheck/src/main/java/backend/pirocheck/User/filter/SessionCheckFilter.java
- backend/pirocheck/src/main/java/backend/pirocheck/User/service/UserService.java
- backend/pirocheck/src/main/resources/application.yml
[feat] feat: 세션 보안 강화 및 만료 시 401 응답 처리 추가
> [feat] feat: 세션 보안 강화 및 만료 시 401 응답 처리 추가

- frontend/src/Attendance.jsx
[add]: Attendance.jsx 세션 기반 인증 요청처리 추가
> [add]: Attendance.jsx 세션 기반 인증 요청처리 추가

- backend/pirocheck/src/main/java/backend/pirocheck/assignment/controller/AssignmentController.java
- backend/pirocheck/src/main/java/backend/pirocheck/config/WebConfig.java
[fix] WebConfig.java 3000번 포트 삭제 및 과제 api 경로 수정
> [fix] WebConfig.java 3000번 포트 삭제 및 과제 api 경로 수정

- backend/pirocheck/src/main/java/backend/pirocheck/config/WebConfig.java
http://pirocheck.org -> http://www.pirocheck.org
> [fix] WebConfig Origin url 수정

- frontend/src/api/api.js
- frontend/src/pages/admin/DetailManageStudent.jsx
- frontend/src/pages/admin/ManageStudent.jsx
[fix]: DetailManageStudent.jsx 데이터 불러오는 로직 수정
> [fix]: DetailManageStudent.jsx 데이터 불러오는 로직 수정

- frontend/src/pages/admin/DetailManageStudent.jsx
- frontend/src/pages/admin/DetailManageStudent.module.css
[add]: DetailManageStudent UI 추가
> [add]: DetailManageStudent UI 추가

- frontend/src/pages/admin/DetailManageStudent.jsx
[fix]: DetailManageStudent error fix
> [fix]: DetailManageStudent error fix

- backend/pirocheck/src/main/java/backend/pirocheck/ManageStudents/dto/response/ManageStudentDetailResDto.java
- backend/pirocheck/src/main/java/backend/pirocheck/ManageStudents/service/ManageStudentsService.java
> [fix] managestudent

- frontend/src/pages/generation/Attendance.jsx
> [fix]: Attendance.jsx api 수정

- backend/pirocheck/src/main/java/backend/pirocheck/Deposit/controller/DepositController.java
- backend/pirocheck/src/main/java/backend/pirocheck/Deposit/dto/DepositResDto.java
- backend/pirocheck/src/main/java/backend/pirocheck/Deposit/entity/Deposit.java
- backend/pirocheck/src/main/java/backend/pirocheck/ManageStudents/Controller/ManageStudentsController.java
- backend/pirocheck/src/main/java/backend/pirocheck/ManageStudents/dto/request/DefenceUpdateReqDto.java
- backend/pirocheck/src/main/java/backend/pirocheck/ManageStudents/dto/response/ManageStudentDetailResDto.java
- backend/pirocheck/src/main/java/backend/pirocheck/ManageStudents/service/ManageStudentsService.java
- backend/pirocheck/src/main/java/backend/pirocheck/User/controller/UserController.java
- backend/pirocheck/src/main/java/backend/pirocheck/User/dto/request/LoginRequest.java
- backend/pirocheck/src/main/java/backend/pirocheck/User/dto/response/LoginResponse.java
[fix] managestudent & 보증금 로직 수정
> [fix] managestudent & 보증금 로직 수정

- frontend/src/components/TaskModal.jsx
[fix]: ManagaTask.jsx save_btn 핸들링 처리 추가
> [fix]: ManagaTask.jsx save_btn 핸들링 처리 추가

- frontend/src/pages/admin/AdminStudentAssignment.jsx
[fix]: 수강생 디테일 페이지 -> 과제확인 페이지 api 넘김 로직 수정
> [fix]: 수강생 디테일 페이지 -> 과제확인 페이지 api 넘김 로직 수정

- backend/pirocheck/src/main/java/backend/pirocheck/ManageStudents/dto/response/ManageStudentDetailResDto.java
- backend/pirocheck/src/main/java/backend/pirocheck/ManageStudents/service/ManageStudentsService.java
> [fix] managestudent ResDto 수정

- backend/pirocheck/src/main/java/backend/pirocheck/Assignment/dto/request/AssignmentCreateReq.java
- backend/pirocheck/src/main/java/backend/pirocheck/Assignment/dto/request/AssignmentUpdateReq.java
- backend/pirocheck/src/main/java/backend/pirocheck/Assignment/dto/response/AssignmentDayRes.java
- backend/pirocheck/src/main/java/backend/pirocheck/Assignment/dto/response/AssignmentWeekRes.java
- backend/pirocheck/src/main/java/backend/pirocheck/Assignment/entity/Assignment.java
- backend/pirocheck/src/main/java/backend/pirocheck/Assignment/service/AssignmentService.java
- subject 컬럼명을 title로 수정
- subtitle 컬럼 추가
> [fix] subtitle 컬럼 추가

- frontend/src/api/students.js
- frontend/src/pages/admin/DetailManageStudent.jsx
- frontend/src/pages/admin/DetailManageStudent.module.css
> [add]: 보증금 방어권 업데이트 로직 추가

- frontend/src/pages/admin/DetailManageStudent.jsx
> [fix]: 보증금 업데이트 로직 수정

- backend/pirocheck/src/main/java/backend/pirocheck/config/WebConfig.java
- frontend/src/pages/generation/Attendance.jsx
[fix]: 특정 날짜 출석 정보 조회-boomImg 로직 수정
> [fix]: 특정 날짜 출석 정보 조회-boomImg 로직 수정

- frontend/src/components/AttendanceWeekInfo.jsx
- frontend/src/pages/generation/Attendance.jsx
> [add]: data 구조 확인용 로그 추가

- frontend/src/pages/generation/Attendance.jsx
> [fix]: 날짜 비교 기준 확인 로직 추가

- frontend/src/pages/generation/Attendance.jsx
[fix]: currentDateRef 업데이트 오류 수정
> [fix]: currentDateRef 업데이트 오류 수정

- backend/pirocheck/src/main/java/backend/pirocheck/Attendance/repository/AttendanceRepository.java
- backend/pirocheck/src/main/java/backend/pirocheck/Attendance/service/AttendanceService.java
> [fix] deposit update

- backend/pirocheck/src/main/java/backend/pirocheck/Assignment/service/AssignmentService.java
> [fix] 과제 세팅 수정
